version: '3.8'

services:
  # Frontend UI Service
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - finnotate-network
    restart: unless-stopped

  # Backend API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - finnotate-network
    restart: unless-stopped
    # Uncomment if you need a database
    # depends_on:
    #   - database

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - finnotate-network
    volumes:
      - 'minio_data:/data'  # Note: different path for official image
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=pk909090090
    command: server /data --address ":9000" --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  seaweedfs_data:
  minio_data:


networks:
  finnotate-network:
    driver: bridge

# Uncomment if using database
# volumes:
#   postgres_data: